# Generated by Django 4.1.4 on 2022-12-27 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cyclecount', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individualcount',
            old_name='location_id',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='location_id',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='product_id',
            new_name='product',
        ),
        migrations.AddField(
            model_name='individualcount',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cyclecount.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='individualcount',
            name='qty',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='individualcount',
            name='state',
            field=models.CharField(choices=[('Active', 'Active'), ('Deleted', 'Deleted')], default='Active', max_length=10),
        ),
    ]
