# Generated by Django 4.1.4 on 2022-12-29 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyclecount', '0002_rename_location_id_individualcount_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countsession',
            old_name='associate',
            new_name='created_by',
        ),
        migrations.AlterField(
            model_name='individualcount',
            name='qty',
            field=models.IntegerField(default=1),
        ),
    ]
