# Generated by Django 4.1.4 on 2022-12-29 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cyclecount', '0003_rename_associate_countsession_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='countsession',
            name='completed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='countsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='countsession',
            name='final_state',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Canceled', 'Canceled')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='countsession',
            name='final_state_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='countsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='countsession',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
