# Generated by Django 4.1.4 on 2023-01-04 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cyclecount', '0005_rename_location_id_cyclecountmodification_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='cyclecountmodification',
            name='new_qty',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cyclecountmodification',
            name='old_qty',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cyclecountmodification',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cyclecount.product'),
            preserve_default=False,
        ),
    ]
