# Generated by Django 4.1.4 on 2023-01-17 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cyclecount', '0006_cyclecountmodification_new_qty_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('location', 'product')},
        ),
    ]
